<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class GrandRestaurant_Templates_Source extends Elementor\TemplateLibrary\Source_Base {

	/**
	 * Template prefix
	 *
	 * @var string
	 */
	protected $template_prefix = 'grandrestaurant_';

	/**
	 * Return templates prefix
	 *
	 * @return [type] [description]
	 */
	public function get_prefix() {
		return $this->template_prefix;
	}

	public function get_id() {
		return 'grandrestaurant-templates';
	}

	public function get_title() {
		return __( 'Grand Restaurant Templates', 'grandrestaurant-elementor' );
	}

	public function register_data() {}

	public function get_items( $args = array() ) {
		
		$templates = array();

		$templates_data = array(
			1 	=> array(
				'template_id'      	=> $this->template_prefix .'1',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 1',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_1.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/',
			),
			2 	=> array(
				'template_id'      	=> $this->template_prefix .'2',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 2',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_2.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/home-2/',
			),
			3 	=> array(
				'template_id'      	=> $this->template_prefix .'3',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 3',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_3.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/home-3/',
			),
			4 	=> array(
				'template_id'      	=> $this->template_prefix .'4',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 4',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_4.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/home-4/',
			),
			5 	=> array(
				'template_id'      	=> $this->template_prefix .'5',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 5',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_5.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/home-5/',
			),
			6 	=> array(
				'template_id'      	=> $this->template_prefix .'6',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Home 6',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_6.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/home-6/',
			),
			7 	=> array(
				'template_id'      	=> $this->template_prefix .'7',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Menu Mixed',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_7.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/menu-mixed/',
			),
			8 	=> array(
				'template_id'      	=> $this->template_prefix .'8',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Menu Classic',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_8.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/menu-classic/',
			),
			9 	=> array(
				'template_id'      	=> $this->template_prefix .'9',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Menu Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_9.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/menu-grid/',
			),
			10 	=> array(
				'template_id'      	=> $this->template_prefix .'10',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Menu Grid Image',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_10.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/menu-grid-image/',
			),
			11 	=> array(
				'template_id'      	=> $this->template_prefix .'11',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Menu Parallax',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_11.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/menu-parallax/',
			),
			12 	=> array(
				'template_id'      	=> $this->template_prefix .'12',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_12.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/about-us/',
			),
			13 	=> array(
				'template_id'      	=> $this->template_prefix .'13',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Our Chefs',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_13.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/our-chefs/',
			),
			14 	=> array(
				'template_id'      	=> $this->template_prefix .'14',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Our Services',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_14.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('team'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/our-services/',
			),
			15 	=> array(
				'template_id'      	=> $this->template_prefix .'15',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Contact Multiple Maps',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_15.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/contact-multiple-maps/',
			),
			16 	=> array(
				'template_id'      	=> $this->template_prefix .'16',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Contact Parallax',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_16.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/contact-parallax/',
			),
			17 	=> array(
				'template_id'      	=> $this->template_prefix .'17',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Contact Gallery',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_17.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('reservation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/contact-gallery/',
			),
			18 	=> array(
				'template_id'      	=> $this->template_prefix .'18',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_18.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-grid/',
			),
			19 	=> array(
				'template_id'      	=> $this->template_prefix .'19',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Grid No Space',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_19.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-grid-no-space/',
			),
			20 	=> array(
				'template_id'      	=> $this->template_prefix .'20',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Masonry',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_20.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-masonry/',
			),
			21 	=> array(
				'template_id'      	=> $this->template_prefix .'21',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Metro',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_21.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-metro/',
			),
			22 	=> array(
				'template_id'      	=> $this->template_prefix .'22',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Metro No Space',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_22.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-metro-no-space/',
			),
			23 	=> array(
				'template_id'      	=> $this->template_prefix .'23',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog Classic',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_23.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-classic/',
			),
			24 	=> array(
				'template_id'      	=> $this->template_prefix .'24',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Blog List',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_24.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/blog-list/',
			),
			25 	=> array(
				'template_id'      	=> $this->template_prefix .'25',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Cuisine - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_25.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo2/',
			),
			26 	=> array(
				'template_id'      	=> $this->template_prefix .'26',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_26.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/',
			),
			27 	=> array(
				'template_id'      	=> $this->template_prefix .'27',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_27.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/menus/',
			),
			28 	=> array(
				'template_id'      	=> $this->template_prefix .'28',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_28.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/about-us/',
			),
			29 	=> array(
				'template_id'      	=> $this->template_prefix .'29',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Gallery',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_29.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/gallery/',
			),
			30 	=> array(
				'template_id'      	=> $this->template_prefix .'30',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Find Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_30.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/find/',
			),
			31 	=> array(
				'template_id'      	=> $this->template_prefix .'31',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bakery - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_31.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo5/',
			),
			32 	=> array(
				'template_id'      	=> $this->template_prefix .'32',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_32.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/',
			),
			33 	=> array(
				'template_id'      	=> $this->template_prefix .'33',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_33.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/menus/',
			),
			34 	=> array(
				'template_id'      	=> $this->template_prefix .'34',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_34.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/about-us/',
			),
			35 	=> array(
				'template_id'      	=> $this->template_prefix .'35',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - Find Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_35.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/find-us/',
			),
			36 	=> array(
				'template_id'      	=> $this->template_prefix .'36',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_36.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/',
			),
			37 	=> array(
				'template_id'      	=> $this->template_prefix .'37',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_37.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/menus/',
			),
			38 	=> array(
				'template_id'      	=> $this->template_prefix .'38',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_38.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/about-us/',
			),
			39 	=> array(
				'template_id'      	=> $this->template_prefix .'39',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Venue Functions',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_39.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('venue'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/venue-functions/',
			),
			40 	=> array(
				'template_id'      	=> $this->template_prefix .'40',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Contact',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_40.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/contact/',
			),
			41 	=> array(
				'template_id'      	=> $this->template_prefix .'41',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_41.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/',
			),
			42 	=> array(
				'template_id'      	=> $this->template_prefix .'42',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_42.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/about/',
			),
			43 	=> array(
				'template_id'      	=> $this->template_prefix .'43',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_43.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/our-menus/',
			),
			44 	=> array(
				'template_id'      	=> $this->template_prefix .'44',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Reservation',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_44.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('reservation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/reservation/',
			),
			45 	=> array(
				'template_id'      	=> $this->template_prefix .'45',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Contact',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_45.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/contact/',
			),
			46 	=> array(
				'template_id'      	=> $this->template_prefix .'46',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_46.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/',
			),
			47 	=> array(
				'template_id'      	=> $this->template_prefix .'47',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_47.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/our-menus/',
			),
			48 	=> array(
				'template_id'      	=> $this->template_prefix .'48',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_48.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/about/',
			),
			49 	=> array(
				'template_id'      	=> $this->template_prefix .'49',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - Find Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_49.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/find-us/',
			),
			50 	=> array(
				'template_id'      	=> $this->template_prefix .'50',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_50.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/',
			),
			51 	=> array(
				'template_id'      	=> $this->template_prefix .'51',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_51.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/about-us/',
			),
			52 	=> array(
				'template_id'      	=> $this->template_prefix .'52',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_52.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('menu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/our-menus/',
			),
			53 	=> array(
				'template_id'      	=> $this->template_prefix .'53',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Locate',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_53.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/locate/',
			),
			54 	=> array(
				'template_id'      	=> $this->template_prefix .'54',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Contact',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_54.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/contact/',
			),
			55 	=> array(
				'template_id'      	=> $this->template_prefix .'55',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_55.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/',
			),
			56 	=> array(
				'template_id'      	=> $this->template_prefix .'56',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_56.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('our-menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/our-menus/',
			),
			57 	=> array(
				'template_id'      	=> $this->template_prefix .'57',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Catering & Events',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_57.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('catering-events'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/catering-events/',
			),
			58 	=> array(
				'template_id'      	=> $this->template_prefix .'58',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Our Location',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_58.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/contact/',
			),
			59 	=> array(
				'template_id'      	=> $this->template_prefix .'59',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_59.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/',
			),
			60 	=> array(
				'template_id'      	=> $this->template_prefix .'60',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_60.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('our-menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/our-menus/',
			),
			61 	=> array(
				'template_id'      	=> $this->template_prefix .'61',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_61.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about-us'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/about-us/',
			),
			62 	=> array(
				'template_id'      	=> $this->template_prefix .'62',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Contact Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_62.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('contact-us'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/contact-us/',
			),
			63 	=> array(
				'template_id'      	=> $this->template_prefix .'63',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_63.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/',
			),
			64 	=> array(
				'template_id'      	=> $this->template_prefix .'64',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_64.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('our-menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/our-menus/',
			),
			65 	=> array(
				'template_id'      	=> $this->template_prefix .'65',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_65.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about-us'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/about-us/',
			),
			66 	=> array(
				'template_id'      	=> $this->template_prefix .'66',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - Reservation',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_66.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('reservation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/reservation/',
			),
			67 	=> array(
				'template_id'      	=> $this->template_prefix .'67',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_67.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/',
			),
			68 	=> array(
				'template_id'      	=> $this->template_prefix .'68',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_68.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/about-us/',
			),
			69 	=> array(
				'template_id'      	=> $this->template_prefix .'69',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_69.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/our-menus/',
			),
			70 	=> array(
				'template_id'      	=> $this->template_prefix .'70',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Blog',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_70.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/blog/',
			),
			71 	=> array(
				'template_id'      	=> $this->template_prefix .'71',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Reservation',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_71.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('reservation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/reservation/',
			),
			72 	=> array(
				'template_id'      	=> $this->template_prefix .'72',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_72.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/',
			),
			73 	=> array(
				'template_id'      	=> $this->template_prefix .'73',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_73.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/about-us/',
			),
			74 	=> array(
				'template_id'      	=> $this->template_prefix .'74',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_74.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/our-menus/',
			),
			75 	=> array(
				'template_id'      	=> $this->template_prefix .'75',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Gallery',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_75.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('gallery'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/gallery/',
			),
			76 	=> array(
				'template_id'      	=> $this->template_prefix .'76',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Contact',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_76.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/contact/',
			),
			77 	=> array(
				'template_id'      	=> $this->template_prefix .'77',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Reservations',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_77.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('reservations'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/reservations/',
			),
			78 	=> array(
				'template_id'      	=> $this->template_prefix .'78',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_78.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/',
			),
			79 	=> array(
				'template_id'      	=> $this->template_prefix .'79',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_79.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/our-menus/',
			),
			80 	=> array(
				'template_id'      	=> $this->template_prefix .'80',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Gallery',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_80.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('gallery'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/gallery/',
			),
			81 	=> array(
				'template_id'      	=> $this->template_prefix .'81',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Contact Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_81.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/contact-us/',
			),
			82 	=> array(
				'template_id'      	=> $this->template_prefix .'82',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_82.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/',
			),
			83 	=> array(
				'template_id'      	=> $this->template_prefix .'83',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_83.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/our-menus/',
			),
			84 	=> array(
				'template_id'      	=> $this->template_prefix .'84',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_84.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/about-us/',
			),
			85 	=> array(
				'template_id'      	=> $this->template_prefix .'85',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Book a Table',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_85.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('book'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/book-a-table/',
			),
			86 	=> array(
				'template_id'      	=> $this->template_prefix .'86',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_86.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/',
			),
			87 	=> array(
				'template_id'      	=> $this->template_prefix .'87',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_87.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/our-menus/',
			),
			88 	=> array(
				'template_id'      	=> $this->template_prefix .'88',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_88.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/about-us/',
			),
			89 	=> array(
				'template_id'      	=> $this->template_prefix .'89',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Book a Table',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_89.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('book'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/book-a-table/',
			),
			90 	=> array(
				'template_id'      	=> $this->template_prefix .'90',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_90.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/',
			),
			91 	=> array(
				'template_id'      	=> $this->template_prefix .'91',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Our Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_91.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('menus'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/our-menus/',
			),
			92 	=> array(
				'template_id'      	=> $this->template_prefix .'92',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - About Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_92.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/about-us/',
			),
			93 	=> array(
				'template_id'      	=> $this->template_prefix .'93',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Book a Table',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_93.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('book'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/book-a-table/',
			),
						
			//Adding navigation menu block templates
			501 => array(
				'template_id'      	=> $this->template_prefix .'501',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_501.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/header/header-transparent/',
			),
			502 => array(
				'template_id'      	=> $this->template_prefix .'502',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Cuisine - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_502.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo2/header/one-page-header-transparent/',
			),
			503 => array(
				'template_id'      	=> $this->template_prefix .'503',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_503.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo3/header/header-solid/',
			),
			504 => array(
				'template_id'      	=> $this->template_prefix .'504',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bakery - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_504.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo5/header/header/',
			),
			505 => array(
				'template_id'      	=> $this->template_prefix .'505',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_505.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/header/header-transparent/',
			),
			506 => array(
				'template_id'      	=> $this->template_prefix .'506',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_506.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/header/header-transparent/',
			),
			507 => array(
				'template_id'      	=> $this->template_prefix .'507',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_507.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/header/header-transparent/',
			),
			508 => array(
				'template_id'      	=> $this->template_prefix .'508',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_508.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/header/header-transparent/',
			),
			509 => array(
				'template_id'      	=> $this->template_prefix .'509',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_509.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/header/header-transparent/',
			),
			510 => array(
				'template_id'      	=> $this->template_prefix .'510',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_510.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/blog/header/header/',
			),
			511 => array(
				'template_id'      	=> $this->template_prefix .'511',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_511.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/header/header/',
			),
			512 => array(
				'template_id'      	=> $this->template_prefix .'512',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_512.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/header/header/',
			),
			513 => array(
				'template_id'      	=> $this->template_prefix .'513',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_513.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/blog/header/header/',
			),
			514 => array(
				'template_id'      	=> $this->template_prefix .'514',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_514.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/header/header/',
			),
			515 => array(
				'template_id'      	=> $this->template_prefix .'515',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_515.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/header/header/',
			),
			516 => array(
				'template_id'      	=> $this->template_prefix .'516',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_516.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/blog/header/header/',
			),
			517 => array(
				'template_id'      	=> $this->template_prefix .'517',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_517.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/header/header/',
			),
			518 => array(
				'template_id'      	=> $this->template_prefix .'518',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_518.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/header/header/',
			),
			
			//Adding mega menu block templates
			601 => array(
				'template_id'      	=> $this->template_prefix .'601',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Mega Menu Home Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_601.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/megamenu/demo-mega-menu/',
			),
			602 => array(
				'template_id'      	=> $this->template_prefix .'602',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Mega Menu Pages',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_602.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/megamenu/page-mega-menu/',
			),
			603 => array(
				'template_id'      	=> $this->template_prefix .'603',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Mega Menu Food Menus',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_603.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/megamenu/food-mega-menu/',
			),
			604 => array(
				'template_id'      	=> $this->template_prefix .'604',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Mega Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_604.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/megamenu/mega-menu/',
			),
			
			//Adding footer block templates
			701 => array(
				'template_id'      	=> $this->template_prefix .'701',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_701.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/footer/footer/',
			),
			702 => array(
				'template_id'      	=> $this->template_prefix .'702',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bakery - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_702.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo5/footer/footer/',
			),
			703 => array(
				'template_id'      	=> $this->template_prefix .'703',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Luxury Restaurant - Footer 3',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_703.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo6/footer/footer/',
			),
			704 => array(
				'template_id'      	=> $this->template_prefix .'704',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Italian Cuisine - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_704.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo7/footer/footer/',
			),
			705 => array(
				'template_id'      	=> $this->template_prefix .'705',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Traditional Food - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_705.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo8/footer/footer/',
			),
			706 => array(
				'template_id'      	=> $this->template_prefix .'706',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fast Food - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_706.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo9/footer/footer/',
			),
			707 => array(
				'template_id'      	=> $this->template_prefix .'707',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Cuisine - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_707.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1612181657 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://themes.themegoods.com/grandrestaurantv6/demo10/',
			),
			708 => array(
				'template_id'      	=> $this->template_prefix .'708',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_708.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/blog/footer/footer/',
			),
			709 => array(
				'template_id'      	=> $this->template_prefix .'709',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_709.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/footer/footer/',
			),
			710 => array(
				'template_id'      	=> $this->template_prefix .'710',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Pizza Restaurant - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_710.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/pizza/footer/footer/',
			),
			711 => array(
				'template_id'      	=> $this->template_prefix .'711',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_711.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/blog/footer/footer/',
			),
			712 => array(
				'template_id'      	=> $this->template_prefix .'712',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Steakhouse - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_712.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/steak/footer/footer/',
			),
			713 => array(
				'template_id'      	=> $this->template_prefix .'713',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_713.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/footer/footer/',
			),
			714 => array(
				'template_id'      	=> $this->template_prefix .'714',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_714.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/blog/footer/footer/',
			),
			715 => array(
				'template_id'      	=> $this->template_prefix .'715',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_715.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/footer/footer/',
			),
			716 => array(
				'template_id'      	=> $this->template_prefix .'716',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_716.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1723613794 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/footer/footer/',
			),
			
			//Adding fullscreen menu block templates
			901 => array(
				'template_id'      	=> $this->template_prefix .'901',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Fusion Food - Make a Reseration',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_901.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/blog/fullmenu/reservation-form/',
			),
			902 => array(
				'template_id'      	=> $this->template_prefix .'902',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Clean Food - Make a Reseration',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_902.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1665986301 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-7.themegoods.com/clean/fullmenu/make-a-reservation/',
			),
			903 => array(
				'template_id'      	=> $this->template_prefix .'903',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Elegant Restaurant - Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_903.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/blog/fullmenu/fullscreen-menu/',
			),
			904 => array(
				'template_id'      	=> $this->template_prefix .'904',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Asian Restaurant - Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_904.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv6-8.themegoods.com/asian/fullmenu/fullscreen-menu/',
			),
			905 => array(
				'template_id'      	=> $this->template_prefix .'905',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Sushi Restaurant - Fullscreen Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_905.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/blog/fullmenu/fullscreen-menu/',
			),
			906 => array(
				'template_id'      	=> $this->template_prefix .'906',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Cocktail & Bar - Mobile Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_906.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bar/fullmenu/mobile-menu/',
			),
			907 => array(
				'template_id'      	=> $this->template_prefix .'907',
				'source'            => $this->get_id(),
				'title'             => 'Grand Restaurant Bistro - Fullscreen Menu',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandrestaurant/templates/screenshots/grandrestaurant_907.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1698913478 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandrestaurantv7-0.themegoods.com/bistro/fullmenu/fullscreen-menu/',
			),
		);
		
		if ( ! empty( $templates_data ) ) {
			foreach ( $templates_data as $template_data ) 
			{
				$templates_data['popularityIndex'] = 260;
				$templates_data['trendIndex'] = 125;
				
				$templates[] = $this->get_item( $template_data );
			}
		}

		if ( ! empty( $args ) ) {
			$templates = wp_list_filter( $templates, $args );
		}
		
		return $templates;
	}
	
	public function get_item( $template_data ) {
		return array(
			'template_id'     => $template_data['template_id'],
			'source'          => 'remote',
			'type'            => $template_data['type'],
			'subtype'         => $template_data['subtype'],
			'title'           => $template_data['title'],
			'thumbnail'       => $template_data['thumbnail'],
			'date'            => $template_data['date'],
			'author'          => $template_data['author'],
			'tags'            => $template_data['keywords'],
			'isPro'           => ( 1 == $template_data['is_pro'] ),
			'popularityIndex' => 260,
			'trendIndex'      => 125,
			'hasPageSettings' => 1,
			'url'             => $template_data['url'],
			'favorite'        => 0,
			'accessLevel'     => 0,
		);
	}

	public function save_item( $template_data ) {
		return false;
	}

	public function update_item( $new_data ) {
		return false;
	}

	public function delete_template( $template_id ) {
		return false;
	}

	public function export_template( $template_id ) {
		return false;
	}

	public function get_data( array $args, $context = 'display' ) {
		$url	  = 'https://assets.themegoods.com/demo/grandrestaurant/templates/json/'.$args['template_id'].'.json';
		$response = wp_remote_get( $url, array( 'timeout' => 60 ) );
		$body     = wp_remote_retrieve_body( $response );
		$body     = json_decode( $body, true );
		$data     = ! empty( $body['content'] ) ? $body['content'] : false;
		
		$result = array();

		$result['content']       = $this->replace_elements_ids($data);
		$result['content']       = $this->process_export_import_content( $result['content'], 'on_import' );
		$result['page_settings'] = array();

		return $result;
	}
}
